/*
global command_array

func check_signature
func decrypt_message
func encrypt_message
func derive_prng_from_master_seed
func derive_new_otp_from_master_seed
func derive_new_aes_from_master_seed
func parse_incoming_command
func parse_outgoing_command
func beacon
func execute_command
*/